import '../../../core/models/project_report.dart';
import '../../../core/models/project_report_section.dart';
import '../../../core/models/project_report_source.dart';
import '../data/reports_repository.dart';

class ReportGenerationService {
  Future<ProjectReport> createManualReport({
    required ReportsRepository repository,
    required String companyId,
    required String projectId,
    required String title,
    required String? authorId,
    DateTime? reportDate,
    String weather = '',
    String progressSummary = '',
    String blockers = '',
    String decisions = '',
    String nextSteps = '',
  }) async {
    final now = DateTime.now();

    final report = ProjectReport(
      id: '',
      companyId: companyId,
      projectId: projectId,
      title: title,
      reportDate: reportDate ?? now,
      weather: weather,
      progressSummary: progressSummary,
      blockers: blockers,
      decisions: decisions,
      nextSteps: nextSteps,
      authorId: authorId,
      isArchived: false,
      createdAt: now,
      updatedAt: now,
      reportType: 'manual',
      sourceModule: 'manual',
      status: 'draft',
    );

    final savedReport = await repository.createReport(report);

    final sections = <ProjectReportSection>[
      ProjectReportSection(
        id: '',
        companyId: companyId,
        reportId: savedReport.id,
        sectionKey: 'manual_notes',
        sectionTitle: 'Notes libres',
        sectionType: 'text',
        sortOrder: 10,
        contentText: '',
        contentJson: const <String, dynamic>{},
        isAutoGenerated: false,
        createdAt: now,
        updatedAt: now,
      ),
    ];

    await repository.replaceSections(
      reportId: savedReport.id,
      sections: sections,
    );

    return savedReport;
  }

  Future<ProjectReport> generateAutomaticReport({
    required ReportsRepository repository,
    required String companyId,
    required String projectId,
    required String title,
    required String sourceModule,
    required String? authorId,
    required DateTime periodStart,
    required DateTime periodEnd,
    required List<ProjectReportSection> sections,
    required List<ProjectReportSource> sources,
    String weather = '',
    String progressSummary = '',
    String blockers = '',
    String decisions = '',
    String nextSteps = '',
  }) async {
    final now = DateTime.now();

    final report = ProjectReport(
      id: '',
      companyId: companyId,
      projectId: projectId,
      title: title,
      reportDate: now,
      weather: weather,
      progressSummary: progressSummary,
      blockers: blockers,
      decisions: decisions,
      nextSteps: nextSteps,
      authorId: authorId,
      isArchived: false,
      createdAt: now,
      updatedAt: now,
      reportType: sourceModule == 'global' ? 'weekly_auto' : 'module_auto',
      sourceModule: sourceModule,
      status: 'generated',
      periodStart: periodStart,
      periodEnd: periodEnd,
      generatedAt: now,
    );

    final savedReport = await repository.createReport(report);

    final normalizedSections = sections
        .map(
          (section) => ProjectReportSection(
            id: '',
            companyId: companyId,
            reportId: savedReport.id,
            sectionKey: section.sectionKey,
            sectionTitle: section.sectionTitle,
            sectionType: section.sectionType,
            sortOrder: section.sortOrder,
            contentText: section.contentText,
            contentJson: section.contentJson,
            isAutoGenerated: section.isAutoGenerated,
            createdAt: now,
            updatedAt: now,
          ),
        )
        .toList();

    final normalizedSources = sources
        .map(
          (source) => ProjectReportSource(
            id: '',
            companyId: companyId,
            reportId: savedReport.id,
            moduleName: source.moduleName,
            sourceEntityType: source.sourceEntityType,
            sourceEntityId: source.sourceEntityId,
            snapshotJson: source.snapshotJson,
            createdAt: now,
            updatedAt: now,
          ),
        )
        .toList();

    await repository.replaceSections(
      reportId: savedReport.id,
      sections: normalizedSections,
    );

    await repository.replaceSources(
      reportId: savedReport.id,
      sources: normalizedSources,
    );

    return savedReport;
  }
}
