import '../../../core/models/project_quote.dart';
import '../../../core/models/project_report.dart';
import '../../../core/models/project_report_section.dart';
import '../../../core/models/project_report_source.dart';
import '../../reports/data/reports_repository.dart';
import '../../reports/services/report_generation_service.dart';

class QuoteReportBridgeService {
  Future<ProjectReport> generateQuoteReport({
    required ReportsRepository reportsRepository,
    required String companyId,
    required String projectId,
    required String projectName,
    required String? authorId,
    required ProjectQuote? quote,
    required DateTime periodStart,
    required DateTime periodEnd,
  }) async {
    final generationService = ReportGenerationService();
    final now = DateTime.now();

    final sections = <ProjectReportSection>[
      ProjectReportSection(
        id: '',
        companyId: companyId,
        reportId: '',
        sectionKey: 'quotes_summary',
        sectionTitle: 'Synthèse devis',
        sectionType: 'text',
        sortOrder: 10,
        contentText: _buildSummary(
          projectName: projectName,
          quote: quote,
          generatedAt: now,
          periodStart: periodStart,
          periodEnd: periodEnd,
        ),
        contentJson: <String, dynamic>{
          'project_name': projectName,
          'has_quote': quote != null,
          'generated_at': now.toIso8601String(),
        },
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      ),
      ProjectReportSection(
        id: '',
        companyId: companyId,
        reportId: '',
        sectionKey: 'quote_parameters',
        sectionTitle: 'Paramètres devis',
        sectionType: 'text',
        sortOrder: 20,
        contentText: _buildParameters(quote),
        contentJson: <String, dynamic>{
          'mode': quote?.mode,
          'status': quote?.status,
          'unit_price_walls': quote?.unitPriceWalls,
          'unit_price_ceiling': quote?.unitPriceCeiling,
        },
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      ),
      ProjectReportSection(
        id: '',
        companyId: companyId,
        reportId: '',
        sectionKey: 'quote_state',
        sectionTitle: 'ÃƒâDA°tat du devis courant',
        sectionType: 'text',
        sortOrder: 30,
        contentText: _buildState(quote),
        contentJson: <String, dynamic>{
          'signed': quote?.signatureBase64 != null &&
              quote!.signatureBase64!.trim().isNotEmpty,
          'sent_at': quote?.sentAt?.toIso8601String(),
          'signed_at': quote?.signedAt?.toIso8601String(),
          'updated_at': quote?.updatedAt.toIso8601String(),
        },
        isAutoGenerated: true,
        createdAt: now,
        updatedAt: now,
      ),
      ProjectReportSection(
        id: '',
        companyId: companyId,
        reportId: '',
        sectionKey: 'free_notes',
        sectionTitle: 'Compléments manuels',
        sectionType: 'text',
        sortOrder: 100,
        contentText: '',
        contentJson: const <String, dynamic>{},
        isAutoGenerated: false,
        createdAt: now,
        updatedAt: now,
      ),
    ];

    final sources = <ProjectReportSource>[
      ProjectReportSource(
        id: '',
        companyId: companyId,
        reportId: '',
        moduleName: 'devis',
        sourceEntityType: 'project_quote',
        sourceEntityId: quote?.id,
        snapshotJson: <String, dynamic>{
          'project_id': projectId,
          'project_name': projectName,
          'quote': quote == null
              ? null
              : <String, dynamic>{
                  'id': quote.id,
                  'mode': quote.mode,
                  'status': quote.status,
                  'unit_price_walls': quote.unitPriceWalls,
                  'unit_price_ceiling': quote.unitPriceCeiling,
                  'sent_at': quote.sentAt?.toIso8601String(),
                  'signed_at': quote.signedAt?.toIso8601String(),
                  'updated_at': quote.updatedAt.toIso8601String(),
                },
        },
        createdAt: now,
        updatedAt: now,
      ),
    ];

    return generationService.generateAutomaticReport(
      repository: reportsRepository,
      companyId: companyId,
      projectId: projectId,
      title: 'Rapport automatique devis - $projectName',
      sourceModule: 'devis',
      authorId: authorId,
      periodStart: periodStart,
      periodEnd: periodEnd,
      sections: sections,
      sources: sources,
      progressSummary: quote == null
          ? 'Aucun devis disponible pour la période.'
          : 'Devis courant disponible avec statut ${quote.status}.',
      blockers: '',
      decisions: '',
      nextSteps: '',
    );
  }

  String _buildSummary({
    required String projectName,
    required ProjectQuote? quote,
    required DateTime generatedAt,
    required DateTime periodStart,
    required DateTime periodEnd,
  }) {
    final period = '${_date(periodStart)} au ${_date(periodEnd)}';
    if (quote == null) {
      return 'Projet : $projectName\n'
          'Période : $period\n'
          'Rapport généré le ${_dateTime(generatedAt)}.\n'
          'Aucun devis nâDAâ„¢a été trouvé pour ce projet.';
    }

    return 'Projet : $projectName\n'
        'Période : $period\n'
        'Rapport généré le ${_dateTime(generatedAt)}.\n'
        'Devis courant détecté.\n'
        'Statut : ${quote.status}.\n'
        'Mode : ${quote.mode}.';
  }

  String _buildParameters(ProjectQuote? quote) {
    if (quote == null) {
      return 'Aucun paramètre devis disponible.';
    }

    return 'Mode : ${quote.mode}\n'
        'Statut : ${quote.status}\n'
        'PU murs : ${quote.unitPriceWalls.toStringAsFixed(2)}\n'
        'PU plafond : ${quote.unitPriceCeiling.toStringAsFixed(2)}';
  }

  String _buildState(ProjectQuote? quote) {
    if (quote == null) {
      return 'Aucun devis courant.';
    }

    final hasSignature = quote.signatureBase64 != null &&
        quote.signatureBase64!.trim().isNotEmpty;

    return 'Dernière mise à jour : ${_dateTime(quote.updatedAt)}\n'
        'Envoyé le : ${quote.sentAt == null ? '-' : _dateTime(quote.sentAt!)}\n'
        'Signé le : ${quote.signedAt == null ? '-' : _dateTime(quote.signedAt!)}\n'
        'Signature client : ${hasSignature ? 'Oui' : 'Non'}';
  }

  String _date(DateTime value) {
    final day = value.day.toString().padLeft(2, '0');
    final month = value.month.toString().padLeft(2, '0');
    final year = value.year.toString().padLeft(4, '0');
    return '$day/$month/$year';
  }

  String _dateTime(DateTime value) {
    final date = _date(value);
    final hour = value.hour.toString().padLeft(2, '0');
    final minute = value.minute.toString().padLeft(2, '0');
    return '$date $hour:$minute';
  }
}
